### ISSUE TITLE
Naive question on 1PDM

### ISSUE THREAD

**Issue by vvp-nsk** [hebrewsnabla/ExSCF#1]
Hej!

Would it be possible to extract 1PDM separately for alpha- and beta-channels for a converged SUHF solution? For the UHF reference, it can be done trivially as following:

```
...
mf = scf.UHF(mol)
mf.chkfile = 'uhf.chk'
mf.init_guess = 'chkfile'
mf.kernel()
mf.analyze()
dma, dmb = mf.make_rdm1()
dm = [dma, dmb]
...
```

But I am puzzled about how to proceed with the SUHF reference WF.

Thank you in advance!

With best regards, 
Victor

**Comment by jeanwsr** [comment]
Yes. For the 1PDM of projected WF, it's `mf.suhf_dm`.

**Comment by vvp-nsk** [comment]
Hej!

Thank you for your prompt reply.  Just to make sure, 'mf.suhf_dm' refers to 1PDM in AO representation, right?

With best regards, 
Victor

**Comment by jeanwsr** [comment]
Yes.

**Comment by vvp-nsk** [comment]
Many thanks!
